title: Your Site Title
description: >-
  A personal site for sharing my thoughts and experiences.
baseurl: ""
url: ""
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap